const ALLOWED_ALLERGENS = [
    "Milk",
    "Egg",
    "Peanut",
    "Tree Nut",
    "Wheat",
    "Soy",
    "Fish",
    "Shellfish",
    "Sesame",
];
const ALLOWED_FOOD_TYPES = [
    "Beef",
    "Breakfast",
    "Chicken",
    "Dessert",
    "First Course",
    "Goat",
    "Lamb",
    "Main Course",
    "Miscellaneous",
    "Pasta",
    "Pork",
    "Seafood",
    "Side",
    "Starter",
    "Vegan",
    "Vegetarian",
];
const ALLOWED_CUISINES = [
    "American",
    "British",
    "Canadian",
    "Chinese",
    "Croatian",
    "Dutch",
    "Egyptian",
    "Filipino",
    "French",
    "Greek",
    "Indian",
    "Irish",
    "Italian",
    "Jamaican",
    "Japanese",
    "Kenyan",
    "Malaysian",
    "Mexican",
    "Moroccan",
    "Polish",
    "Portuguese",
    "Russian",
    "Spanish",
    "Thai",
    "Tunisian",
    "Turkish",
    "Ukrainian",
    "Uruguayan",
    "Vietnamese"
];

module.exports = {
    ALLOWED_ALLERGENS,
    ALLOWED_FOOD_TYPES,
    ALLOWED_CUISINES,
};